title: "Interstella: Token Cosmos Traversal for AGI Emergence"
description: Engineering AGI through semantic traversals inspired by Interstellar.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://interstella.ai-avatar.org" # the base hostname & protocol for your site, e.g. http://example.com
lang: en
languages: [ "en", "zh-CN" ]
default_lang: en
exclude_from_localization: [ "node_modules", "vendor", ".git", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "CNAME", "assets/images", "assets/css", "assets/js", "_site", "sitemap.xml", "feed.xml" ]
parallel_localization: true
i18n_headers: true

# Permalink settings
permalink: /:categories/:year/:month/:day/:title.html

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Jerry Zhang"
      lang: "en"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      author: "Jerry Zhang"
      lang: "en"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-polyglot
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 5
paginate_path: /page:num/

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
